# Generated by Django 4.0.4 on 2022-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestations',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
