# Generated by Django 4.0.4 on 2022-07-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_prestations_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
