# Generated by Django 4.0.4 on 2022-07-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityoccurrence',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='availabilityoccurrence',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='padding_for',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='room',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='AvailabilityOccurrence',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomReservation',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
